const mockItems = [
  {
    id: "1",
    imageUrl: "../assets/images/balanza-touch-pro.png",
    title: "Balanza Touch Pro",
    description: [
      "Balanza touch digital PRO",
      "- Posee 4 programas (Full automatic, manual, semi automatic y ratio mode)",
      "- Unidades intercambiables (gr,ml,Oz)",
      "- Touch digital",
      "- Timer",
      "- apagado automatico y seteable.",
      "- Carga con USB (incluye cable)",
      "- Peso maximo 2 kilos",
      "- Toma cada 0.1 gr.",
      "- Indicador de batería",
    ],
    category: "accesorios",
    price: "2500",
    stock: 5,
  },
  {
    id: "2",
    imageUrl: "../assets/images/botellas___14544_zoom.png",
    title: "Botella de Acero Termica",
    description: [
      "Botella Eco Friendly",
      "Mantiene el frio por 24hs y el calor por 12hs.",
      "Con capacidad de 500ml",
      "Apto para alimentos.",
      "Ayudá a reducir el uso de botellas plásticas.",
      "LLEVA TU BEBIDA A TODOS LADOS, AYUDANDO A CUIDAR EL PLANETA",
    ],
    category: "accesorios",
    price: "3400",
    stock: 10,
  },
  {
    id: "3",
    imageUrl: "../assets/images/dolce_gosto_portada__06221_zoom.png",
    title: "Capsulas Recargables Dolce Gusto Caffettino",
    description: [
      "Recarga tus capsulas con Cafe de Especialidad!",
      "Cápsulas Recargables CAFFETTINO son la mejor manera de utilizar tu Dolce.",
      "Te permiten crear tus propios blends y ahorrar, al mismo tiempo que no contaminas en cada café.",
      "- Mas de 100 recargas con cada cápsula!",
      "- Únicas con CABEZAL PRESURIZADOR PATENTADO que permite obtener un café cremoso.",
      "- Únicas con Difusor que permite hacer cafés cortos o largos.",
      "- Únicas con POSICIONADOR para facilitar la colocación en el portacapsulas.",
      "- Diseño de todas sus piezas encastrables. Imposible de perder las partes!",
      "- NO necesitan de NINGUN AGREGADO para funcionar. Solo Café!",
      "- Usalas con el CAFE tostado o torrado que mas te guste, TE o YERBA MATE.",
      "- Libres de BPA, aptas para estar en contacto con alimentos.",
      "- NO SE DEFORMAN, se las puede dejar en agua hirviendo.",
      "- Super SIMPLES DE LIMPIAR, incluso en lava vajilla.",
      "- Se pueden guardar las capsulas llenas en la heladera durante una semana.",
      "- LA CANTIDAD JUSTA para recibir invitados y tener todas las capsulas cargadas.",
      "- Atención. NO SON CHINAS!",
      "- No compatibles con modelo LUMIO!",
    ],
    category: "capsulas",
    price: "1500",
    stock: 4,
  },
  {
    id: "4",
    imageUrl: "../assets/images/capsulas_domestic_portada__39017_zoom.png",
    title: "Capsulas Reutilizables linea Domestic",
    description: [
      "Recarga tus capsulas con Cafe de Especialidad!",
      "Cápsulas Recargables son la mejor manera de utilizar tu Nespresso o Dolce Gusto!",
      "Te permiten crear tus propios blends y ahorrar, al mismo tiempo que no contaminas en cada café.",
      "- 50 recargas con cada cápsula!",
      "- NO necesitan de NINGUN AGREGADO para funcionar. Solo Café!",
      "- Usalas con el CAFE tostado que mas te guste, TE o YERBA MATE.",
      "- Libres de BPA, aptas para estar en contacto con alimentos.",
      "- NO SE DEFORMAN, se las puede dejar en agua hirviendo.",
      "- Super SIMPLES DE LIMPIAR, incluso en lava vajilla.",
      "- Se pueden guardar las capsulas llenas en la heladera durante una semana.",
      "- LA CANTIDAD JUSTA para recibir invitados y tener todas las capsulas cargadas.",
      "¿Por qué no sale agua de la máquina/sale un poco y luego para/ o rebalsa?",
      "Esto puede ocurrir principalmente porque la molienda de café utilizada es extra fina, produciendo que durante el proceso de presión el agua quede atascada en la cápsula. A su vez, asegurarse de compactar muy suavemente el café y cerrar firmemente la cápsula. Si ya se cuenta con un café extra fino, probar rellenar la cápsula en 3/4 (no hasta el tope) y presionar suavemente.",
    ],
    category: "capsulas",
    price: "1300",
    stock: 3,
  },
  {
    id: "5",
    imageUrl: "../assets/images/caffetino_portada__35075_zoom.png",
    title: "Capsulas Recargables Nespresso Caffettino",
    description: [
      "Recarga tus capsulas con Cafe de Especialidad!",
      "Cápsulas Recargables CAFFETTINO son la mejor manera de utilizar tu Nespresso.",
      "Te permiten crear tus propios blends y ahorrar, al mismo tiempo que no contaminan.",
      "No dejes de ver los videos para ver su funcionamiento.",
      "- Mas de 80 recargas con cada cápsula!",
      "- Únicas con TAPA PRESURIZADORA PATENTADA que permite obtener un café cremoso.",
      "- Usalas con el CAFE tostado que mas te guste, TE o YERBA MATE.",
      "- Libres de BPA, aptas para estar en contacto con alimentos.",
      "- NO SE DEFORMAN, se las puede dejar en agua hirviendo.",
      "- Super SIMPLES DE LIMPIAR, incluso en lava vajilla.",
      "- Se pueden guardar las capsulas llenas en la heladera durante una semana.",
      "- LA CANTIDAD JUSTA para recibir invitados y tener todas las capsulas cargadas.",
      "- Atención. NO SON CHINAS!",
    ],
    category: "capsulas",
    price: "4200",
    stock: 6,
  },
  {
    id: "6",
    imageUrl: "../assets/images/server_vidrio_mb__97898_zoom.png",
    title: "Jarra De Vidrio Server",
    description: [
      "JARRA SERVER DE VIDRIO",
      "Fundamental para completar tu kit barista!",
      "Resistente al calor, útil tanto para la elaboración como para el servicio del café.",
      "Está especialmente diseñada para ser utilizada con cono de goteo V60 de Hario u otros métodos como Aeropress o Kalita.",
      "Material de Vidrio",
      "Con tapa.",
    ],
    category: "accesorios",
    price: "6000",
    stock: 1,
  },
  {
    id: "7",
    imageUrl: "../assets/images/stan_up_web__55258_zoom.png",
    title: "Bolsa Con Valvula Stand Up Pouch 200 Gr",
    description: [
      "LA MEJOR FORMA DE FRACCIONAR TU CAFE",
      "BOLSAS CON INTERIOR DE ALUMINIO.",
      "Cierre Zipper",
      "CON VÁLVULA",
      "MEDIDAS:",
      "ALTO 21 CMS",
      "ANCHO 16 CMS",
      "CAPACIDAD 1/4",
      "CON ALUMINIO POR DENTRO. SISTEMA ZIPPER.",
    ],
    category: "accesorios",
    price: "71",
    stock: 4,
  },
  {
    id: "8",
    imageUrl: "../assets/images/delter_y_eco__31694_zoom.png",
    title: "Cafetera Delter + eco vaso",
    description: [
      "DELTER COFFE PRESS + ECOVASO",
      "Delter Coffee Press, se inventó en Australia y fue lanzada a finales de 2018 con una campaña financiada a través de Kickstarter. Su inventor también es el responsable de Trinity One, Mark Folker. Cuando vemos la DCP no podemos evitar pensar y hacer comparaciones con la Aeropress debido a su parecido exterior. Sin embargo, la funcionalidad de DCP es sustancialmente diferente, produciendo una taza más parecida a un filtrado, pero con una dosificación de agua y agitación más controladas.",
      "Producto nuevo en caja original (incluyendo los 100 filtros de papel originales).",
      "Pequeña",
      "Liviana",
      "Fácil de limpiar",
      "Compacta",
      "La tapa funciona como cuchara",
    ],
    category: "cafeteras",
    price: "9450",
    stock: 3,
  },
  {
    id: "9",
    imageUrl: "../assets/images/calma-te-serenidad.png",
    title: "Calma Té Serenidad",
    description: ["Blend con té verde y digestivo"],
    category: "cafe_te",
    price: "350",
    stock: 3,
  },
  {
    id: "10",
    imageUrl: "../assets/images/patagonia-soul.png",
    title: "Patagonia Soul Consciencia",
    description: [
      "Té rojo con frutilla, frambuesa, arándano, rosa mosqueta y lavanda",
    ],
    category: "cafe_te",
    price: "750",
    stock: 1,
  },
];

export default mockItems;
